USE [master]
GO

/****** Object:  Database [SequenceTest]    Script Date: 1/31/2026 11:34:41 AM ******/
CREATE DATABASE [SequenceTest]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'SequenceTest', 
  --Altered: FILENAMEs are altered for the target environment
  FILENAME = N'E:\MSSQLFIles\MSSQL17.MSSQLSERVER\MSSQL\Data\SequenceTest.mdf' , 
  SIZE = 1GB , MAXSIZE = 30GB, FILEGROWTH = 1GB )
 LOG ON 
( NAME = N'SequenceTest_log', 
  FILENAME = N'E:\MSSQLFIles\MSSQL17.MSSQLSERVER\MSSQL\Data\SequenceTest_log.ldf' ,
  SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, 
 LEDGER = OFF
GO

--Altered: Turned on DELAYED_DURABILITY
ALTER DATABASE [SequenceTest] SET DELAYED_DURABILITY = FORCED
GO

--Altered: Turned off full text indexing
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [SequenceTest].[dbo].[sp_fulltext_database] @action = 'disable'
end
GO

--Altered: Turned on READ_COMMITTED_SNAPSHOT
ALTER DATABASE [SequenceTest] SET READ_COMMITTED_SNAPSHOT ON 
GO

--Altered: Turned on Accelerated Database Recovery (creating tables with a
--billion rows got complicated
ALTER DATABASE [SequenceTest] SET ACCELERATED_DATABASE_RECOVERY = ON  
GO

--Altered: Turned on SIMPLE RECOVERY to minimize logging (
--and I won't be recovering anything.
ALTER DATABASE [SequenceTest] SET RECOVERY SIMPLE 
GO

--All others left as defaults


ALTER DATABASE [SequenceTest] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [SequenceTest] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [SequenceTest] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [SequenceTest] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [SequenceTest] SET ARITHABORT OFF 
GO

ALTER DATABASE [SequenceTest] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [SequenceTest] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [SequenceTest] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [SequenceTest] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [SequenceTest] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [SequenceTest] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [SequenceTest] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [SequenceTest] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [SequenceTest] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [SequenceTest] SET  ENABLE_BROKER 
GO

ALTER DATABASE [SequenceTest] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [SequenceTest] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [SequenceTest] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [SequenceTest] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [SequenceTest] SET PARAMETERIZATION SIMPLE 
GO



ALTER DATABASE [SequenceTest] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [SequenceTest] SET  MULTI_USER 
GO

ALTER DATABASE [SequenceTest] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [SequenceTest] SET DB_CHAINING OFF 
GO

ALTER DATABASE [SequenceTest] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [SequenceTest] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO


ALTER DATABASE [SequenceTest] SET OPTIMIZED_LOCKING = OFF 
GO

ALTER DATABASE [SequenceTest] SET QUERY_STORE = ON
GO

ALTER DATABASE [SequenceTest] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO

ALTER DATABASE [SequenceTest] SET  READ_WRITE 
GO


